#!/usr/bin/env bash
# Install and configure the load balancer

sudo apt-get update
sudo apt-get -y install haproxy


echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3280-web-01 34.139.198.222 check 
    server 3280-web-02 34.74.158.179 check 
" >> /etc/haproxy/haproxy.cfg
service haproxy restart