#!/usr/bin/env bash
# Install and configure the load balancer

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*


echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3280-web-01 34.139.198.222 check 
    server 3280-web-02 34.74.158.179 check 
" >> /etc/haproxy/haproxy.cfg
service haproxy restart