#!/usr/bin/env bash
# This script is displaying "bad luck" in 4 position
# "good luck" in the 8 position
n=0
while [ $n -le 10 ]
do
    if [ $n -eq 4 ]
    then
        echo "bad luck"
    elif [ $n -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((n++))
done