#!/usr/bin/env bash
# This script is displaying ...
n=1
while [ $n -le 20 ]
do
    echo "$n"
    case $n in
    5)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    18)
        echo "bad luck from Italy"
        ;;
    esac
    ((n++))
done
    