#!/usr/bin/env bash
# This script is displaying ...
n=1
while [ $n -le 20 ]
do
    echo "$n"
    case $n in
        4)
        echo "bad luck from China"
        ;;
        8)
        echo "bad luck from Japan"
        ;;
        17)
        echo "bad luck from Italy"
        ;;
    esac
    ((n++))
done
    