#!/usr/bin/env bash
# This script is displaying ...
n=1
while [ $n -le 20 ]
do
    case $n in
    5)
        echo "bad luck from china"
        ;;
    9)
        echo "bad luck in japan"
        ;;
    18)
        echo "bad luck from italy"
        ;;
    esac
    echo "$n"
    ((n++))
done
    